export default cards = [
  {
    id: 1,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "M19 Airpods TWS (True Wireless Stereo) Bluetooth Earbuds",
    price: 200,
    discount: 20,
    coinsSave: 100,
    rating: 4.5,
    reviewCount: 200,
    sold: 770,
  },
  {
    id: 2,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Wireless Noise-Canceling Headphones",
    price: 300,
    discount: 15,
    coinsSave: 150,
    rating: 4.7,
    reviewCount: 320,
    sold: 890,
  },
  {
    id: 3,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Bluetooth Speaker Mini Portable",
    price: 120,
    discount: 10,
    coinsSave: 50,
    rating: 4.3,
    reviewCount: 150,
    sold: 600,
  },
  {
    id: 4,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Smart Fitness Band Tracker",
    price: 80,
    discount: 25,
    coinsSave: 20,
    rating: 4.6,
    reviewCount: 500,
    sold: 1500,
  },
  {
    id: 5,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "4K Action Camera Waterproof",
    price: 250,
    discount: 18,
    coinsSave: 80,
    rating: 4.4,
    reviewCount: 220,
    sold: 450,
  },
  {
    id: 6,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Gaming Mouse High Precision",
    price: 50,
    discount: 30,
    coinsSave: 15,
    rating: 4.8,
    reviewCount: 340,
    sold: 1200,
  },
  {
    id: 7,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Laptop Cooling Pad Adjustable",
    price: 35,
    discount: 12,
    coinsSave: 10,
    rating: 4.2,
    reviewCount: 100,
    sold: 400,
  },
  {
    id: 8,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Smart Home Assistant Speaker",
    price: 180,
    discount: 22,
    coinsSave: 60,
    rating: 4.9,
    reviewCount: 700,
    sold: 2000,
  },
  {
    id: 9,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Wireless Charging Pad",
    price: 40,
    discount: 20,
    coinsSave: 10,
    rating: 4.0,
    reviewCount: 180,
    sold: 550,
  },
  {
    id: 10,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Digital Alarm Clock LED Display",
    price: 25,
    discount: 15,
    coinsSave: 5,
    rating: 4.1,
    reviewCount: 120,
    sold: 350,
  },
  {
    id: 11,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "M19 Airpods TWS (True Wireless Stereo) Bluetooth Earbuds",
    price: 200,
    discount: 20,
    coinsSave: 100,
    rating: 4.5,
    reviewCount: 200,
    sold: 770,
  },
  {
    id: 12,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Wireless Noise-Canceling Headphones",
    price: 300,
    discount: 15,
    coinsSave: 150,
    rating: 4.7,
    reviewCount: 320,
    sold: 890,
  },
  {
    id: 13,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Bluetooth Speaker Mini Portable",
    price: 120,
    discount: 10,
    coinsSave: 50,
    rating: 4.3,
    reviewCount: 150,
    sold: 600,
  },
  {
    id: 14,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Smart Fitness Band Tracker",
    price: 80,
    discount: 25,
    coinsSave: 20,
    rating: 4.6,
    reviewCount: 500,
    sold: 1500,
  },
  {
    id: 15,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "4K Action Camera Waterproof",
    price: 250,
    discount: 18,
    coinsSave: 80,
    rating: 4.4,
    reviewCount: 220,
    sold: 450,
  },
  {
    id: 16,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Gaming Mouse High Precision",
    price: 50,
    discount: 30,
    coinsSave: 15,
    rating: 4.8,
    reviewCount: 340,
    sold: 1200,
  },
  {
    id: 17,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Laptop Cooling Pad Adjustable",
    price: 35,
    discount: 12,
    coinsSave: 10,
    rating: 4.2,
    reviewCount: 100,
    sold: 400,
  },
  {
    id: 18,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Smart Home Assistant Speaker",
    price: 180,
    discount: 22,
    coinsSave: 60,
    rating: 4.9,
    reviewCount: 700,
    sold: 2000,
  },
  {
    id: 19,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Wireless Charging Pad",
    price: 40,
    discount: 20,
    coinsSave: 10,
    rating: 4.0,
    reviewCount: 180,
    sold: 550,
  },
  {
    id: 20,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Digital Alarm Clock LED Display",
    price: 25,
    discount: 15,
    coinsSave: 5,
    rating: 4.1,
    reviewCount: 120,
    sold: 350,
  },
  {
    id: 21,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "M19 Airpods TWS (True Wireless Stereo) Bluetooth Earbuds",
    price: 200,
    discount: 20,
    coinsSave: 100,
    rating: 4.5,
    reviewCount: 200,
    sold: 770,
  },
  {
    id: 22,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Wireless Noise-Canceling Headphones",
    price: 300,
    discount: 15,
    coinsSave: 150,
    rating: 4.7,
    reviewCount: 320,
    sold: 890,
  },
  {
    id: 23,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Bluetooth Speaker Mini Portable",
    price: 120,
    discount: 10,
    coinsSave: 50,
    rating: 4.3,
    reviewCount: 150,
    sold: 600,
  },
  {
    id: 24,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Smart Fitness Band Tracker",
    price: 80,
    discount: 25,
    coinsSave: 20,
    rating: 4.6,
    reviewCount: 500,
    sold: 1500,
  },
  {
    id: 25,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "4K Action Camera Waterproof",
    price: 250,
    discount: 18,
    coinsSave: 80,
    rating: 4.4,
    reviewCount: 220,
    sold: 450,
  },
  {
    id: 26,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Gaming Mouse High Precision",
    price: 50,
    discount: 30,
    coinsSave: 15,
    rating: 4.8,
    reviewCount: 340,
    sold: 1200,
  },
  {
    id: 27,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Laptop Cooling Pad Adjustable",
    price: 35,
    discount: 12,
    coinsSave: 10,
    rating: 4.2,
    reviewCount: 100,
    sold: 400,
  },
  {
    id: 28,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Smart Home Assistant Speaker",
    price: 180,
    discount: 22,
    coinsSave: 60,
    rating: 4.9,
    reviewCount: 700,
    sold: 2000,
  },
  {
    id: 29,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Wireless Charging Pad",
    price: 40,
    discount: 20,
    coinsSave: 10,
    rating: 4.0,
    reviewCount: 180,
    sold: 550,
  },
  {
    id: 30,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Digital Alarm Clock LED Display",
    price: 25,
    discount: 15,
    coinsSave: 5,
    rating: 4.1,
    reviewCount: 120,
    sold: 350,
  },
  {
    id: 31,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "M19 Airpods TWS (True Wireless Stereo) Bluetooth Earbuds",
    price: 200,
    discount: 20,
    coinsSave: 100,
    rating: 4.5,
    reviewCount: 200,
    sold: 770,
  },
  {
    id: 32,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Wireless Noise-Canceling Headphones",
    price: 300,
    discount: 15,
    coinsSave: 150,
    rating: 4.7,
    reviewCount: 320,
    sold: 890,
  },
  {
    id: 33,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Bluetooth Speaker Mini Portable",
    price: 120,
    discount: 10,
    coinsSave: 50,
    rating: 4.3,
    reviewCount: 150,
    sold: 600,
  },
  {
    id: 34,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Smart Fitness Band Tracker",
    price: 80,
    discount: 25,
    coinsSave: 20,
    rating: 4.6,
    reviewCount: 500,
    sold: 1500,
  },
  {
    id: 35,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "4K Action Camera Waterproof",
    price: 250,
    discount: 18,
    coinsSave: 80,
    rating: 4.4,
    reviewCount: 220,
    sold: 450,
  },
  {
    id: 36,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Gaming Mouse High Precision",
    price: 50,
    discount: 30,
    coinsSave: 15,
    rating: 4.8,
    reviewCount: 340,
    sold: 1200,
  },
  {
    id: 37,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Laptop Cooling Pad Adjustable",
    price: 35,
    discount: 12,
    coinsSave: 10,
    rating: 4.2,
    reviewCount: 100,
    sold: 400,
  },
  {
    id: 38,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Smart Home Assistant Speaker",
    price: 180,
    discount: 22,
    coinsSave: 60,
    rating: 4.9,
    reviewCount: 700,
    sold: 2000,
  },
  {
    id: 39,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Wireless Charging Pad",
    price: 40,
    discount: 20,
    coinsSave: 10,
    rating: 4.0,
    reviewCount: 180,
    sold: 550,
  },
  {
    id: 40,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Digital Alarm Clock LED Display",
    price: 25,
    discount: 15,
    coinsSave: 5,
    rating: 4.1,
    reviewCount: 120,
    sold: 350,
  },
  {
    id: 41,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "M19 Airpods TWS (True Wireless Stereo) Bluetooth Earbuds",
    price: 200,
    discount: 20,
    coinsSave: 100,
    rating: 4.5,
    reviewCount: 200,
    sold: 770,
  },
  {
    id: 42,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Wireless Noise-Canceling Headphones",
    price: 300,
    discount: 15,
    coinsSave: 150,
    rating: 4.7,
    reviewCount: 320,
    sold: 890,
  },
  {
    id: 43,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Bluetooth Speaker Mini Portable",
    price: 120,
    discount: 10,
    coinsSave: 50,
    rating: 4.3,
    reviewCount: 150,
    sold: 600,
  },
  {
    id: 44,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Smart Fitness Band Tracker",
    price: 80,
    discount: 25,
    coinsSave: 20,
    rating: 4.6,
    reviewCount: 500,
    sold: 1500,
  },
  {
    id: 45,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "4K Action Camera Waterproof",
    price: 250,
    discount: 18,
    coinsSave: 80,
    rating: 4.4,
    reviewCount: 220,
    sold: 450,
  },
  {
    id: 46,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Gaming Mouse High Precision",
    price: 50,
    discount: 30,
    coinsSave: 15,
    rating: 4.8,
    reviewCount: 340,
    sold: 1200,
  },
  {
    id: 47,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Laptop Cooling Pad Adjustable",
    price: 35,
    discount: 12,
    coinsSave: 10,
    rating: 4.2,
    reviewCount: 100,
    sold: 400,
  },
  {
    id: 48,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Smart Home Assistant Speaker",
    price: 180,
    discount: 22,
    coinsSave: 60,
    rating: 4.9,
    reviewCount: 700,
    sold: 2000,
  },
  {
    id: 49,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Wireless Charging Pad",
    price: 40,
    discount: 20,
    coinsSave: 10,
    rating: 4.0,
    reviewCount: 180,
    sold: 550,
  },
  {
    id: 50,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Digital Alarm Clock LED Display",
    price: 25,
    discount: 15,
    coinsSave: 5,
    rating: 4.1,
    reviewCount: 120,
    sold: 350,
  },
  {
    id: 51,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "M19 Airpods TWS (True Wireless Stereo) Bluetooth Earbuds",
    price: 200,
    discount: 20,
    coinsSave: 100,
    rating: 4.5,
    reviewCount: 200,
    sold: 770,
  },
  {
    id: 52,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Wireless Noise-Canceling Headphones",
    price: 300,
    discount: 15,
    coinsSave: 150,
    rating: 4.7,
    reviewCount: 320,
    sold: 890,
  },
  {
    id: 53,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Bluetooth Speaker Mini Portable",
    price: 120,
    discount: 10,
    coinsSave: 50,
    rating: 4.3,
    reviewCount: 150,
    sold: 600,
  },
  {
    id: 54,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Smart Fitness Band Tracker",
    price: 80,
    discount: 25,
    coinsSave: 20,
    rating: 4.6,
    reviewCount: 500,
    sold: 1500,
  },
  {
    id: 55,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "4K Action Camera Waterproof",
    price: 250,
    discount: 18,
    coinsSave: 80,
    rating: 4.4,
    reviewCount: 220,
    sold: 450,
  },
  {
    id: 56,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Gaming Mouse High Precision",
    price: 50,
    discount: 30,
    coinsSave: 15,
    rating: 4.8,
    reviewCount: 340,
    sold: 1200,
  },
  {
    id: 57,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Laptop Cooling Pad Adjustable",
    price: 35,
    discount: 12,
    coinsSave: 10,
    rating: 4.2,
    reviewCount: 100,
    sold: 400,
  },
  {
    id: 58,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: false,
    coins: true,
    title: "Smart Home Assistant Speaker",
    price: 180,
    discount: 22,
    coinsSave: 60,
    rating: 4.9,
    reviewCount: 700,
    sold: 2000,
  },
  {
    id: 59,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: true,
    title: "Wireless Charging Pad",
    price: 40,
    discount: 20,
    coinsSave: 10,
    rating: 4.0,
    reviewCount: 180,
    sold: 550,
  },
  {
    id: 60,
    imgsrc:
      "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
    freeDelivery: true,
    coins: false,
    title: "Digital Alarm Clock LED Display",
    price: 25,
    discount: 15,
    coinsSave: 5,
    rating: 4.1,
    reviewCount: 120,
    sold: 350,
  },
];
